### ISSUE TITLE
Missing the templates folder

### ISSUE THREAD

**Issue by snario** [gilles/pyramid_debugtoolbar_mongo#4]
`pyramid_debugtoolbar_mongo/pyramid_debugtoolbar_mongo/panels/templates` is not in the `pypi` package. (https://github.com/gilles/pyramid_debugtoolbar_mongo/tree/master/pyramid_debugtoolbar_mongo/panels/templates)

```bash
$ cd ~/.virtualenv/.../lib/python2.7/site-packages/pyramid_debugtoolbar_mongo/panels/
$ pwd
__init__.py   __init__.pyc  mongo.py      mongo.pyc
```

Not an issue for me working but when I need others to pip install a requirements file it becomes an issue

**Comment by gilles** [comment]
Should be good now
